name: Auto Continuous Analysis Runners

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      commit:
        required: false
        type: string
    secrets:
      ORG_WIDE_TOKEN:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  actions: read
  contents: write
  issues: write

jobs:
  prepare-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Download Latest Artifact
        env:
          GH_TOKEN: ${{ secrets.ORG_WIDE_TOKEN }}
        run: |
          echo "GH_TOKEN length: ${#GH_TOKEN}"
      
          ARTIFACT_JSON=$(gh api "repos/ContinuousAnalysis/requests/actions/artifacts" --paginate)
          ARTIFACT_NAME=$(echo "$ARTIFACT_JSON" | jq -r '.artifacts[] | select(.name | startswith("continuous-analysis-results-requests-")) | .name' | head -n 1)
          ARTIFACT_ID=$(echo "$ARTIFACT_JSON" | jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .id")
      
          if [ -z "$ARTIFACT_ID" ]; then
            echo "No matching artifact found. Skipping download."
            mkdir -p previous-artifacts
            exit 0
          fi
      
          echo "Found artifact: $ARTIFACT_NAME (ID: $ARTIFACT_ID)"
          curl -L \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/ContinuousAnalysis/requests/actions/artifacts/$ARTIFACT_ID/zip" \
            -o artifact.zip
      
          unzip artifact.zip -d previous-artifacts

      - name: Prepare Artifact Data to be used in the auto-runner workflow
        id: prepare-artifact
        run: |
          # If the previous artifact is found, encode it
          if [ -f "previous-artifacts/continuous_analysis_over_time_results.csv" ]; then
            echo "Previous artifact found, moving to the root of the repository"
            mv previous-artifacts/continuous_analysis_over_time_results.csv .
            echo "Previous artifact moved successfully"

          # If the previous artifact is not found, skip the moving
          else
            echo "No previous artifact found, skipping encoding"
          fi

          # Clean up the artifact directory
          rm -rf previous-artifacts/
    
  auto-runner:
    needs: prepare-and-trigger
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Debug Docker Path and Version
        run: |
          echo "PATH is: $PATH"
          which docker
          docker --version

      - name: Restore Previous Artifact from Input
        run: |
          if [ -n "${{ inputs.previous-artifact-data }}" ]; then
            echo "Decoding previous artifact data..."
            echo "${{ inputs.previous-artifact-data }}" | base64 -d > continuous_analysis_over_time_results.csv
            echo "Previous artifact restored successfully"
          else
            echo "No previous artifact data provided"
          fi

      - name: Checkout Testing Repository and create three copies for each analysis
        run: |
          REPO_URL="https://github.com/${{ inputs.project }}.git"
          REPO_NAME=$(basename "${{ inputs.project }}")
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          
          git clone "$REPO_URL" "$REPO_NAME"
          cd "$REPO_NAME"

          if [ -n "${{ inputs.commit }}" ]; then
            echo "Checking out specific commit: ${{ inputs.commit }}"
            git checkout ${{ inputs.commit }}
          else
            echo "Using default branch"
          fi

          cd ..

          cp -r "$REPO_NAME" "$REPO_NAME-original"
          echo "Created $REPO_NAME-original"
          cp -r "$REPO_NAME" "$REPO_NAME-pymop"
          echo "Created $REPO_NAME-pymop"
          cp -r "$REPO_NAME" "$REPO_NAME-dylin"
          echo "Created $REPO_NAME-dylin"

      - name: Checkout Continuous-Analysis Repository
        uses: actions/checkout@v4
        with:
          repository: ContinuousAnalysis/continuous-analysis
          path: continuous-analysis

      - name: Run Original Test
        run: |
          # Create a virtual environment and run the original test
          python3 -m venv original-venv
          source original-venv/bin/activate
          chmod +x continuous-analysis/scripts/run_original.sh
          continuous-analysis/scripts/run_original.sh $REPO_NAME
          deactivate
          rm -rf original-venv

      - name: Build PyMOP Docker Image
        run: |
          sudo docker build -t pymop-runner continuous-analysis/docker_files

      - name: Run PyMOP on Testing Repository
        id: run_pymop
        shell: bash
        run: |
          # Run the PyMOP test in the Docker container
          docker run --rm \
            -v "${{ github.workspace }}:/local" \
            pymop-runner \
            bash -c "set -euxo pipefail && \
            ls -la /local && \
            cp /local/continuous-analysis/scripts/run_pymop.sh /workspace/run_pymop.sh && \
            cp -r /local/$REPO_NAME-pymop /workspace && \
            rm -rf /local/$REPO_NAME-pymop && \
            source /workspace/pymop-venv/bin/activate && \
            chmod +x /workspace/run_pymop.sh && \
            /workspace/run_pymop.sh $REPO_NAME && \
            deactivate"

      - name: Run DyLin on Testing Repository
        run: |
          # Create a virtual environment and run the test with DyLin
          python3 -m venv dylin-venv
          source dylin-venv/bin/activate
          chmod +x continuous-analysis/scripts/run_dylin.sh
          continuous-analysis/scripts/run_dylin.sh $REPO_NAME
          deactivate
          rm -rf dylin-venv
          rm -rf $REPO_NAME-dylin

      - name: Parse Continuous-Analysis Output for Violations
        run: |
          # Parse the continuous-analysis-output folder
          python3 continuous-analysis/scripts/parse_continuous_analysis_output.py $REPO_NAME ${{ inputs.commit }}

      - name: Track changes from the previous commit
        run: |
          # Install the requirements for the script
          pip install -r continuous-analysis/requirements.txt
          echo
          
          # Only run the script if a commit is provided
          if [ -n "${{ inputs.commit }}" ]; then
            python3 continuous-analysis/scripts/filter_new_violations.py $REPO_NAME-original ${{ inputs.commit }}
          else
            echo "No commit provided, skipping change tracking"
          fi

      - name: Generate timestamp
        id: timestamp
        run: |
          ts=$(date +'%Y%m%d-%H%M')
          echo "ts=$ts" >> "$GITHUB_OUTPUT"
          echo "Generated timestamp: $ts"

      - name: Upload Violation Reports
        uses: actions/upload-artifact@v4
        with:
          name: continuous-analysis-results-${{ env.REPO_NAME }}-${{ steps.timestamp.outputs.ts }}
          path: |
            continuous_analysis_over_time_results.csv
            continuous_analysis_results_*.csv
            continuous-analysis-output/
          retention-days: 30
