name: Auto Continuous Analysis Runners

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      commit:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  issues: write

jobs:
  auto-runner:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Debug Docker Path and Version
        run: |
          echo "PATH is: $PATH"
          which docker
          docker --version

      - name: Checkout Testing Repository and create three copies for each analysis
        run: |
          REPO_URL="https://github.com/${{ inputs.project }}.git"
          REPO_NAME=$(basename "${{ inputs.project }}")
          
          git clone "$REPO_URL" "$REPO_NAME"
          cd "$REPO_NAME"

          if [ -n "${{ inputs.commit }}" ]; then
            echo "Checking out specific commit: ${{ inputs.commit }}"
            git checkout ${{ inputs.commit }}
          else
            echo "Using default branch"
          fi

          cd ..

          cp -r "$REPO_NAME" "$REPO_NAME-original"
          echo "Created $REPO_NAME-original"
          cp -r "$REPO_NAME" "$REPO_NAME-pymop"
          echo "Created $REPO_NAME-pymop"
          cp -r "$REPO_NAME" "$REPO_NAME-dylin"
          echo "Created $REPO_NAME-dylin"

      - name: Checkout Continuous-Analysis Repository
        uses: actions/checkout@v4
        with:
          repository: ContinuousAnalysis/continuous-analysis
          path: continuous-analysis

      - name: Run Original Test
        run: |
          # Extract just the repository name (without owner)
          REPO_NAME=$(echo "${{ inputs.project }}" | sed 's/.*\///')

          # Create a virtual environment and run the original test
          python3 -m venv original-venv
          source original-venv/bin/activate
          chmod +x continuous-analysis/scripts/run_original.sh
          continuous-analysis/scripts/run_original.sh $REPO_NAME
          deactivate
          rm -rf original-venv

      - name: Track changes from the previous commit
        run: |
          # Extract just the repository name (without owner)
          REPO_NAME=$(echo "${{ inputs.project }}" | sed 's/.*\///')
          
          echo "Debug: REPO_NAME = $REPO_NAME"
          echo "Debug: Commit = ${{ inputs.commit }}"
          echo "Debug: Current directory = $(pwd)"
          echo "Debug: Directory contents:"
          ls -la
          
          pip install -r continuous-analysis/requirements.txt
          
          # Only run the script if a commit is provided
          if [ -n "${{ inputs.commit }}" ]; then
            echo "Debug: Running script with repo path: $REPO_NAME-original"
            python3 continuous-analysis/scripts/filter_new_violations.py $REPO_NAME-original ${{ inputs.commit }}
          else
            echo "No commit provided, skipping change tracking"
          fi

      # COMMENT OUT THESE ACTIONS FOR TESTING PURPOSES

      # - name: Build PyMOP Docker Image
      #   run: |
      #     sudo docker build -t pymop-runner continuous-analysis/docker_files

      # - name: Run PyMOP on Testing Repository
      #   id: run_pymop
      #   shell: bash
      #   run: |
      #     # Extract just the repository name (without owner)
      #     REPO_NAME=$(echo "${{ inputs.project }}" | sed 's/.*\///')

      #     # Run the PyMOP test in the Docker container
      #     docker run --rm \
      #       -v "${{ github.workspace }}:/local" \
      #       pymop-runner \
      #       bash -c "set -euxo pipefail && \
      #       ls -la /local && \
      #       cp /local/continuous-analysis/scripts/run_pymop.sh /workspace/run_pymop.sh && \
      #       cp -r /local/$REPO_NAME-pymop /workspace && \
      #       rm -rf /local/$REPO_NAME-pymop && \
      #       source /workspace/pymop-venv/bin/activate && \
      #       chmod +x /workspace/run_pymop.sh && \
      #       /workspace/run_pymop.sh $REPO_NAME && \
      #       deactivate"

      # - name: Run DyLin on Testing Repository
      #   run: |
      #     # Extract just the repository name (without owner)
      #     REPO_NAME=$(echo "${{ inputs.project }}" | sed 's/.*\///')

      #     # Create a virtual environment and run the test with DyLin
      #     python3 -m venv dylin-venv
      #     source dylin-venv/bin/activate
      #     chmod +x continuous-analysis/scripts/run_dylin.sh
      #     continuous-analysis/scripts/run_dylin.sh $REPO_NAME
      #     deactivate
      #     rm -rf dylin-venv
      #     rm -rf $REPO_NAME-dylin

      # - name: Parse Continuous-Analysis Output for Violations
      #   run: |
      #     # Extract just the repository name (without owner)
      #     REPO_NAME=$(echo "${{ inputs.project }}" | sed 's/.*\///')
          
      #     # Parse the continuous-analysis-output folder
      #     python3 continuous-analysis/scripts/parse_continuous_analysis_output.py $REPO_NAME
          
      #     # Set the repository name as an environment variable for the next step
      #     echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      # - name: Upload Violation Reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: continuous-analysis-results-${{ env.REPO_NAME }}-${{ github.run_id }}
      #     path: |
      #       continuous-analysis-results_*.csv
      #       continuous-analysis-output/
      #     retention-days: 30
