name: PyMOP Auto Runner

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  issues: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout Auto-PyMOP Repository
        uses: actions/checkout@v4
        with:
          repository: ContinuousAnalysis/auto-pymop
          path: auto-pymop

      - name: Debug Directory Structure
        run: |
          echo "Current working directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Auto-pymop directory contents (if exists):"
          ls -la auto-pymop/ 2>/dev/null || echo "auto-pymop directory does not exist"
          cd ..
          echo "Current working directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Auto-pymop directory contents (if exists):"
          ls -la auto-pymop/ 2>/dev/null || echo "auto-pymop directory does not exist"
          cd ..
          echo "Current working directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Auto-pymop directory contents (if exists):"
          ls -la auto-pymop/ 2>/dev/null || echo "auto-pymop directory does not exist"

      - name: Install Python Dependencies
        run: |
          pip install -r auto-pymop/requirements.txt

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER

      - name: Build Docker Image
        run: |
          sudo docker build -t pymop-runner auto-pymop/docker_files

      - name: Debug Docker Path
        run: |
          echo "PATH is: $PATH"
          which docker
          docker --version

      - name: Run PyMOP on updated projects
        id: run_pymop
        shell: bash
        run: |
          python3 auto-pymop/scripts/track_changes.py
          # Check if changed_projects.txt exists
          if [ -f changed_projects.txt ]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Parse PyMOP Output for Violations
        if: steps.run_pymop.outputs.changes_detected == 'true'
        run: |
          python3 auto-pymop/scripts/parse_pymop_output.py

      - name: Upload Violation Reports
        if: steps.run_pymop.outputs.changes_detected == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: pymop-violations-${{ github.run_id }}
          path: |
            auto-pymop/pymop_results_*.csv
            auto-pymop/pymop_over_time_results.csv
            auto-pymop/changed_projects.txt
          retention-days: 30

      - name: Compare PyMOP Output with Previous Run and Report New Violations
        if: steps.run_pymop.outputs.changes_detected == 'true'
        run: |
          python3 auto-pymop/scripts/track_violations.py

      - name: Clean up unneeded files
        if: steps.run_pymop.outputs.changes_detected == 'true'
        run: |
          rm -f auto-pymop/pymop_results_*.csv
          rm -f auto-pymop/changed_projects.txt
